#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.screenlayout/display.sh
feh --bg-scale ~/dotfiles/images/4455.jpg
$HOME/.config/polybar/launch.sh


# fix java apps
wmname LG3D


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          20
bspc config focused_border_color "#ffffff"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^3'
bspc rule -a GoLand desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
