#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# fix java apps
wmname LG3D


bspc monitor -d I II III IV V VI VII VIII IX X


bspc config split_ratio          0.52
bspc config border_width         2
bspc config window_gap          20
bspc config normal_border_color "#1A1B26"
bspc config focused_border_color "#ffffff"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium deskktop='^3'
bspc rule -a Discord deskktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.screenlayout/display.sh
picom &
feh --bg-scale /home/alex/Downloads/wallhaven-rde7oq_1920x1080.png
$HOME/.config/polybar/launch.sh
