#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config focused_border_color "#aa706575"
bspc config active_border_color "#101010"
bspc config normal_border_color "#101010"

wmname LG3D

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         1
bspc config window_gap           4
bspc config split_ratio          0.52


bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# 1 > web
bspc rule -a Chromium desktop='^1'
bspc rule -a firefox desktop='^1' follow=on manage=of

# 2 > code
bspc rule -a Code desktop='^2' follow=on

# 3 > social-media
bspc rule -a discord desktop='^3'
bspc rule -a telegram desktop='^3'

# 4 > files
bspc rule -a Thunar desktop='^4' follow=on

#picom &
feh --bg-scale /home/alex/dotfiles/images/4006.png
$HOME/.config/polybar/launch.sh

